# Generated by Django 5.0 on 2023-12-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_image',
            new_name='image',
        ),
    ]
